### PR TITLE
don't crash in case we have unicode email addresses

### PR DESCRIPTION
**Pull request by antocuni**
This PR is needed to handle unicode email addresses. Without the PR, the send_messages() crashes if you pass a ``to` or ``from`` email address which has type ``unicode`` (even if it contains only ASCII chars)

### CODE REVIEW

**Comment by rafleze** [comment]
Thanks

**Comment by antocuni** [comment]
you're welcome. Could you please do a new PyPI release with the fix? So that I can just put django-nullmailer in the requirements without having to install it from my fork :).
Thanks.

**Comment by rafleze** [comment]
Done! ;)

**Comment by antocuni** [comment]
Thank!

**Pull request merged**
